### ISSUE TITLE
Source map comment not added

### ISSUE THREAD

**Issue by KrisBraun** [markbates/coffee-rails-source-maps#14]
Source maps are being generated, but no comment pointing to the map is being added to the served js assets. I'm using Rails 3.2.14, coffee-rails 3.2.2 and coffeescript 2.2.0.

The other thing I notice is the file field of the map file is blank:

    {    
      "version": 3,
      "file": "",
      "sourceRoot": "",
      "sources": [
        "/assets/source_maps/app/assets/javascripts/auto/app.coffee"
      ],
      "names": [],
      "mappings": "AACA;CAAA,CAAA,..."
    }

**Comment by markbates** [comment]
I do not maintain this gem anymore. Please fork it, or use a fork.
