### ISSUE TITLE
Doesn't work for me: OSX, Rails 3.2.15, Chrome version 31.0.1650.57

### ISSUE THREAD

**Issue by jmuheim** [markbates/coffee-rails-source-maps#17]
I've done exactly what you write in the README, and the `sourceMappingUrl` seems to be appended correctly, but Chrome still displays everything in JS, not CoffeeScript:

![registrierung_-_inquisiv-2](https://f.cloud.github.com/assets/1814983/1606572/4cec218e-544c-11e3-88ae-86dfa833310d.png)

I have definitely activated the feature itself in Chrome:

![window_and_registrierung_-_inquisiv-2](https://f.cloud.github.com/assets/1814983/1606576/67d48d38-544c-11e3-81ab-68b76a7e6a04.png)

Any idea what's going on? I also emptied the whole `tmp` directory of Rails.

**Comment by markbates** [comment]
I do not maintain this gem anymore. Please fork it, or use a fork.
