### ISSUE TITLE
Doesn't work with config.assets.debug = false

### ISSUE THREAD

**Issue by nornagon** [markbates/coffee-rails-source-maps#22]
I have `config.assets.debug = false` in my development environment, because otherwise every pageload requests 100+ scripts separately. I'd like to use coffee-rails-source-maps to be able to still see which file an error came from, but in this configuration only the last source map gets read and every line is interpreted as being from the last file (alphabetically) in my app.

**Comment by jeffmicklos** [comment]
:+1: I am in the same boat here...

**Comment by markbates** [comment]
I do not maintain this gem anymore. Please fork it, or use a fork.
